"""Update the User Stories & Acceptance sheet with honest, verified status.

Writes ONLY Story Status (col X), Progress % (col Y) and Notes (col AD) for the
specific stories that have been implemented and verified against the running
stack. Everything else is left untouched. Status values follow Lists & Legend.
"""

from __future__ import annotations

from pathlib import Path
import sys

import openpyxl

# Beside this script, not in the working directory: the tracker and the
# scripts that edit it live together in tools/tracker, and a relative
# name would quietly create or miss a copy wherever the script is run from.
FILE = str(Path(__file__).resolve().with_name("Chirala_Bay_Resort_PMS_Development_Tracker (2).xlsx"))

# Legend stage -> Progress fraction.
STAGE = {
    "Not Started": 0.0,
    "UX/UI": 0.1,
    "Backend": 0.35,
    "Frontend": 0.55,
    "Integration": 0.75,
    "QA": 0.9,
    "Done": 1.0,
    "Blocked": 0.0,
}

# Story ID -> (stage, note). Only genuinely-built/verified items.
UPDATES = {
    "US-058-01": ("Done", "Deposit Schedule (mockup 058) view at /reservations/{id}/deposits: header (guest, occupancy, room type, stay, nights) + tab strip; 5 KPI cards (Total Booking Value, Total Deposit Required + %, Total Received + % of scheduled, Balance Due, Next Due Date with overdue/in-N-days); instalment table (#, instalment + %, amount, due date, status, received on, method, reminder, actions) with paid/balance sub-row per row and a Show cancelled toggle. Booking value is real: booking-core /reservations/{id}/detail now returns booking_value = sum over units of nights x (rate_calendar_days rate, else room type base rate), cancelled units at zero. Verified in Chrome on CBR39535923: 3 nights x 6500 = Rs 19,500."),
    "US-058-02": ("Done", "Primary workflow: generate a schedule from percentage splits (20/10/balance-on-arrival), add/edit instalment (fixed amount or % of booking), cancel, collect payment, waive, refund/reverse, and reminder state. Collections go through the SAME finance.post_payment path as every other payment, so each posts a real credit to the reservation folio and appears in Payments; deposit_allocations records which instalment a payment settled. paid_amount is NOT stored - it is SUM(allocations) - so the schedule cannot disagree with the ledger. Status is derived (paid / partially paid / pending / waived); only cancelled is set by a person. Verified in Chrome: collected Rs 1,500 against a Rs 3,900 instalment -> Partially Paid, balance Rs 2,400, Rs 1,500 credit on the folio; waived Rs 1,950 -> Waived, balance moved Rs 18,000 -> Rs 16,050, next due date recalculated; reminder marked sent."),
    "US-058-03": ("Done", "Security/exceptions: RBAC payments.view/create/edit/cancel/approve, deny-by-default. NOTE: the payments permission rows had existed since IAM 0001 but were granted to NO role - every check denied everyone; iam 0007_payments_grants now grants them to Front Desk (view/create/edit), Reservations (view), Resort Manager, Administrator and Property IT Administrator. Waivers over Rs 5,000 need payments.approve: a request from someone without it is stored as 'requested' and the balance does NOT move until decided (verified: anita.reddy/Front Desk waived Rs 9,000 -> requested, status stayed Pending, balance unchanged Rs 13,650; admin approved -> applied; front desk got 403 on waiver-decision). Also verified: over-collection 422, double refund 422, cancelling a paid instalment 422, regenerating an existing schedule 409, optimistic-lock 409 on edit. Append-only audit for generate/create/update/cancel/collect/refund/waive/decision/reminder. GAPS STATED ON THE SCREEN: reminders are recorded, not sent (no mail/SMS transport exists), and waiver approval is decided in place because screen 042's queue still has no request-creation path."),
    "US-003-01": ("Done", "Reservation Calendar / room rack (mockup 003) view at /reservations, now the module's landing screen with the mockup's Calendar / List View toggle (the previous flat table became /reservations/list). GET /booking/reservation-calendar returns rooms grouped by room type, occupancy bars, and stats for a date window (capped at 92 days). Every bar is read from booking.room_calendar_entries - the same table the GiST exclusion constraint guards - so reservations and maintenance blocks come from one source and the rack cannot disagree with what the system will allow. 14-day window with prev/next/Today, Room Type and Status filters, weekend shading, the mockup's 4-colour legend (Confirmed / Tentative=held / Checked In / Blocked), and bars clipped to the window marked with arrows so a partial bar is not read as a short stay. NOTE: the mockup's Booking Source filter is deliberately absent - booking.reservations has no such column, and a dead dropdown would be worse than none. Layout follows the mockup: KPI cards are icon-chip + label + value + delta, filters carry their labels, room-type bands are colour-tinted and collapsible, and the legend sits bottom-left of the grid with the 'Showing <range> | N of M rooms booked' count bottom-right. The Selected Booking panel is rendered ONLY when a bar is picked - the rack takes the full width otherwise - so the panel is the answer to a question rather than a permanent empty card. Verified in Chrome: 44 rooms, AC repair blocks on 143/144, tinted bands for Garden Villa / Pay Test Suite / Reset Test, footer legend and count."),
    "US-003-02": ("Done", "Primary workflow - room assignment from the rack. Bookings with no room are returned in an UNASSIGNED LANE per room type (35 of 35 units are unassigned today, so this is the screen's real work queue); overlapping bars are packed into sub-rows so 35 same-date bookings do not draw on top of each other, in a bounded scroll area so the queue cannot push the rooms off screen. Room types with zero rooms still appear when they hold bookings (Garden Villa has bookings and no keys) - the group is created on demand, or those bookings would silently vanish. Selecting a bar fills the Selected Booking panel (guest, reservation no., check in/out, nights, guests) and, for an unassigned one, offers only rooms of the right type that are free for the whole stay, with View Reservation into the list drawer. 4 KPI cards (Total Bookings, Occupancy, Available Tonight, Room Revenue) with vs-previous-period deltas; occupancy uses the hotel definition - maintenance nights are removed from the denominator, not counted as sold. Verified in Chrome: assigned CBR24201 to room 101, bar moved from the queue onto the room lane, real room_calendar_entry written; reverted afterwards by id."),
    "US-003-03": ("Done", "Security/exceptions: RBAC rooms.view deny-by-default on the calendar read; assert_property_in_org blocks cross-tenant reads; window over 92 days -> 422, end<=start -> 422, unknown status -> 422. Assignment goes through the existing flow.assign_room, so the GiST exclusion constraint is the arbiter, not this UI: verified that assigning CBR24202 to room 101 while CBR24201 held 4-6 Sep was rejected with 409 'Room ... is not available for the requested period'. The UI also filters taken rooms out of the picker, but that is a convenience - the database is what makes double-booking impossible."),
    "US-005-01": ("Done", "Guest Check-In (mockup 005). /front-desk is now the Arrivals list (was a placeholder): GET /booking/arrivals for a date, including anyone still unchecked from earlier days, with search, a show-checked-in toggle and a Check in action per row. The check-in screen itself is the mockup's three panels - Guest Verification / Stay & Room / Payment & Deposit - fed by one call, GET /reservation-units/{id}/check-in-view, which returns the guest, the ID on file, the ID scans, the rooms actually free for the whole stay, and the folio position. Total Stay Amount uses the folio once it has debits and the quoted nights x room-type rate before that, so it is never a made-up number. Verified in Chrome: CBR24107, 16 arrivals on 7 Sep, 3 free rooms offered."),
    "US-005-02": ("Done", "Primary workflow: POST /reservation-units/{id}/complete-check-in does identity, room, deposit and stay in ONE transaction, in that order - identity first, room through flow.assign_room, money only after the room is secured, flow.check_in last - so a half-finished check-in cannot exist. Creates the guest record when the booking had none and links it to the reservation. Records the act in a new booking.stay_checkins row (deposit, verification flags, who did it). Migration 0015 adds guest identity (address, ID type/number, verified-by) and engagement.guest_documents for ID scans, stored in MinIO with only the key in the database and reads served as expiring presigned URLs; replacing a scan deletes the old object as well as the row. Also added the (property_id, id) unique on reservation_units that the rest of the schema uses for tenant-safe FKs and that this table needed. Verified end to end: Sowmya Reddy into room 101, guest created with Aadhaar recorded, unit checked_in, stay in_house, checkin row with all flags."),
    "US-005-03": ("Done", "Security/exceptions: RBAC front_desk.view / front_desk.edit, deny-by-default. NOTE: front_desk permissions were granted only to Administrator (view/create) - the role literally called Front Desk could not have checked anyone in; iam 0008_front_desk_grants fixes that for Front Desk, Reservations, Housekeeping, Resort Manager, Administrator and Property IT Administrator. Verified: checking in twice -> 409 'already checked in'; the same room for an overlapping stay -> 409 'That room was taken while this screen was open' (the GiST exclusion constraint, not a UI check); a deposit with no folio -> 422 rather than taking money with nowhere to post it; a cancelled/completed reservation -> 422. ID uploads are limited to JPEG/PNG/WebP/PDF under 8MB. Append-only audit for reservation_unit.check_in and guest.document.upload/delete. GAPS STATED ON THE SCREEN: 'Room key issued' and 'Welcome message sent' are recorded, not performed - there is no door-lock integration and no mail/SMS transport - and completing a check-in with either ticked returns a warning saying so."),
    "US-007-03": ("Done", "Security/exceptions: RBAC front_desk.view / front_desk.edit, deny-by-default (granted by iam 0008). Verified: checking out twice -> 409 'already checked out'; a unit that is not checked in -> 422 'Only a guest who is in house can leave'; a payment with no folio -> 422 rather than taking money with nowhere to post it. A REMAINING BALANCE DOES NOT BLOCK DEPARTURE but must be confirmed: without allow_outstanding_balance the request is refused with the amount named, and when confirmed the figure is written into stay_checkouts.balance_at_checkout and returned as a warning. Guests do leave owing money - a company is invoiced, a charge is disputed - and refusing checkout would not stop that, only stop it being recorded. Append-only audit reservation_unit.check_out. GAPS STATED ON THE SCREEN: 'Feedback link scheduled' is recorded, not sent (no mail/SMS transport). NOT BUILT, and deliberately not faked: Transfer Charge, Split Bill, Apply Discount and Process Refund from the mockup each need backend that does not exist yet."),
    "US-053-01": ("Done", "Room Move and Upgrade (mockup 053) at /front-desk/room-move/{unitId}, reached from the Departures row and from the check-in screen (which previously dead-ended by refusing a re-assignment and pointing at a screen that did not exist). GET /reservation-units/{id}/room-move-view returns the guest with phone/email, current stay, current room card and stay balance; GET .../move-candidates returns room cards - photo, type, bed, view, floor - for rooms free for EVERY remaining night, with a readiness badge read from operations.room_condition (Ready / Being cleaned / Needs cleaning) rather than the mockup's uncomputable 'Due in 1 hr'; GET .../move-quote prices the move before anyone commits. Layout follows the mockup: Current Room (Move From) beside Replacement Room (Move To / Upgrade) with Room Type / Effective Date / Time filters, then Move-Upgrade Details and Rate Difference (Per Night). Verified in Chrome on Meera Krishnan: 13 free rooms, room 101 correctly badged Needs cleaning, rate panel showing current vs new rate, nights applicable and total."),
    "US-053-02": ("Done", "Primary workflow: POST /reservation-units/{id}/room-move. A move is TWO FACTS, not an edit - this room until a moment, that room after it - so the old room's room_calendar_entry is SHORTENED to the effective time and the new room gets its own entry for the rest of the stay. Nights already slept stay attached to the room they were slept in, which is what housekeeping, a minibar dispute and any later audit need. An in-house guest's stay follows them: the open stay_room_segment is closed and a new one opened, so the stay records both rooms and their times. Also updates assigned_room_id and, when the target is a different type, the unit's room_type_id so the reservation stops claiming a room type the guest is not in. Rate difference is charged to the folio as a room_upgrade debit unless unticked (a complimentary upgrade is a move with no money). Notify Housekeeping genuinely marks the vacated room dirty. Reference numbers are RMU-YYYYMMDD-NNN, unique per property. Migration 0017 adds booking.room_moves capturing the decision AND the rates at the time, because room rates change and asking later what an upgrade cost is only answerable if written down then. Verified end to end: Meera moved 201 -> 203 effective 7 Sep 14:00, entry on 201 shortened to 7 Sep 14:00, new active entry on 203 from 7 Sep 14:00 to 8 Sep 11:00, unit reassigned, third stay segment created, room 201 marked dirty."),
    "US-053-03": ("Done", "Security/exceptions: RBAC front_desk.view / front_desk.edit deny-by-default. The new calendar entry is inserted through the SAME GiST exclusion constraint everything else uses, so a room taken since the screen loaded fails with 409 'was taken while this screen was open' and the guest keeps their old room - the candidate filter is convenience, the constraint is the guarantee. Verified: moving into the room the guest is already in -> 422; a unit with no assigned room -> 422 pointing at assignment instead; a room not active/in_service -> 422; an effective date on or after departure -> 422; an overstay or ended stay returns an EMPTY candidate list rather than erroring on a degenerate date range (found and fixed: it was a 500). AN UPGRADE ABOVE THE Rs 5,000 THRESHOLD IS NOT PERFORMED - it is recorded as pending_approval and the guest stays put, because approval routing still does not exist (042 has a queue but no path into it) and quietly moving someone while imagining the paperwork would be worse than waiting; the screen's button changes to 'Request Upgrade Approval' and says so. Append-only audit room_move.completed / room_move.requested. GAP STATED ON THE SCREEN: 'Reissue Key Card' is recorded, not done - no door-lock integration."),
    "US-010-03": ("Done", "Security/exceptions. These routes were written before chirala_common existed and had NO permission check and NO audit: anyone who could reach the gateway could list every guest, read every folio and post a payment. All 28 endpoints across booking-core routes.py and finance routes.py now carry build_authz guards (require_permission where a property_id is in scope, require_org_permission otherwise). PREREQUISITE FOUND AND FIXED: the guests resource was granted to zero roles and reservations/dashboard to one or two, so guarding first would have locked every role out of the product; iam 0009_core_grants grants them (this is the third such migration after payments in 0007 and front_desk in 0008). SECOND PREREQUISITE: the gateway's /flows/* endpoints called booking-core and finance ANONYMOUSLY, so the aggregation was itself the hole that kept those routes open - the flow client now forwards the caller's token, and each service applies its own checks to the real user. ALSO FIXED a latent bug in the shared authz library: _GRANT_SQL used a bare :prop in both `IS NULL` and a comparison, which Postgres cannot type when an org-scoped check passes NULL - every require_org_permission call was a 500 waiting to happen. Verified: anonymous GET/POST on reservations, guests, folios, payments and /flows/dashboard all return 401; the same calls with a valid token return 200; Dashboard, Guests and Reservations still load in Chrome."),
    "US-028-03": ("Done", "Security/exceptions. These routes were written before chirala_common existed and had NO permission check and NO audit: anyone who could reach the gateway could list every guest, read every folio and post a payment. All 28 endpoints across booking-core routes.py and finance routes.py now carry build_authz guards (require_permission where a property_id is in scope, require_org_permission otherwise). PREREQUISITE FOUND AND FIXED: the guests resource was granted to zero roles and reservations/dashboard to one or two, so guarding first would have locked every role out of the product; iam 0009_core_grants grants them (this is the third such migration after payments in 0007 and front_desk in 0008). SECOND PREREQUISITE: the gateway's /flows/* endpoints called booking-core and finance ANONYMOUSLY, so the aggregation was itself the hole that kept those routes open - the flow client now forwards the caller's token, and each service applies its own checks to the real user. ALSO FIXED a latent bug in the shared authz library: _GRANT_SQL used a bare :prop in both `IS NULL` and a comparison, which Postgres cannot type when an org-scoped check passes NULL - every require_org_permission call was a 500 waiting to happen. Verified: anonymous GET/POST on reservations, guests, folios, payments and /flows/dashboard all return 401; the same calls with a valid token return 200; Dashboard, Guests and Reservations still load in Chrome."),
    "US-065-03": ("Done", "Security/exceptions. These routes were written before chirala_common existed and had NO permission check and NO audit: anyone who could reach the gateway could list every guest, read every folio and post a payment. All 28 endpoints across booking-core routes.py and finance routes.py now carry build_authz guards (require_permission where a property_id is in scope, require_org_permission otherwise). PREREQUISITE FOUND AND FIXED: the guests resource was granted to zero roles and reservations/dashboard to one or two, so guarding first would have locked every role out of the product; iam 0009_core_grants grants them (this is the third such migration after payments in 0007 and front_desk in 0008). SECOND PREREQUISITE: the gateway's /flows/* endpoints called booking-core and finance ANONYMOUSLY, so the aggregation was itself the hole that kept those routes open - the flow client now forwards the caller's token, and each service applies its own checks to the real user. ALSO FIXED a latent bug in the shared authz library: _GRANT_SQL used a bare :prop in both `IS NULL` and a comparison, which Postgres cannot type when an org-scoped check passes NULL - every require_org_permission call was a 500 waiting to happen. Verified: anonymous GET/POST on reservations, guests, folios, payments and /flows/dashboard all return 401; the same calls with a valid token return 200; Dashboard, Guests and Reservations still load in Chrome."),
    "US-029-01": ("Done", "Modify or Cancel Reservation (mockup 029) at /reservations/{id}/modify, reached from the reservations drawer. Two tabs - Modify Stay and Cancel Reservation - as the mockup has them. Modify shows the Current vs Proposed comparison side by side with a live price difference; GET /reservations/{id}/change-view returns the booking, the room types, the property's cancellation policy and whether the booking can be changed at all. Cancel shows the policy text beside the arithmetic it produced. Migration 0018 adds property.cancellation_policies (free_until_days, penalty_nights, approval threshold and the wording the guest is shown, seeded with the mockup's own policy) and booking.reservation_changes, append-only with before/after JSON - a booking modified three times is three decisions, each with a price, and 'what changed on the 14th' must be answerable without replaying state. Verified in Chrome on CBR39535923."),
    "US-029-02": ("Done", "Primary workflow: POST /reservations/{id}/modify-quote prices the proposed stay against the same rate resolution the rest of the system uses AND re-checks availability using the same physical_capacity - out_of_service - held - reserved - allotment sum inventory.py uses, plus this reservation's own hold (it is being moved, not added); POST .../modify applies it. POST .../cancel releases the room calendar entries, returns reserved_units to inventory, posts the policy penalty as a cancellation_fee debit and sets reservation + units to cancelled. GET .../cancel-quote prices it first. Modifying RELEASES an assigned room, because new dates or a new room type may not suit it, and says so - silently keeping it would misstate where the guest is sleeping. Verified: Anil Kapoor 3 -> 4 nights posted +Rs 6,500 to the folio; kishore cancelled with penalty Rs 6,500, refund estimate Rs 7,530, rooms and inventory released. 'cancelled' is now a status the product can actually reach - the Cancelled filter on the reservations list was permanently empty before this."),
    "US-029-03": ("Done", "Security/exceptions: RBAC reservations.view / edit / cancel, deny-by-default; waiving the cancellation penalty additionally needs reservations.approve (403 without). Verified: cancelling twice -> 422; departure on or before arrival -> 422; a stay with no inventory configured -> refused with the date named rather than failing at save; a checked-in or checked-out booking -> 422 pointing at Room Move or Check-out instead. A CANCELLATION WHOSE REFUND EXCEEDS THE POLICY THRESHOLD IS RECORDED AS pending_approval AND THE BOOKING STAYS LIVE - 042 has a queue but still no path into it, and cancelling on an imagined approval would leave a guest with neither a room nor their money. Cancelling does NOT move money: the refund is estimated and flagged, and processing it is a folio action. Append-only audit reservation.modified / reservation.cancelled / reservation.cancellation_requested. Also fixed: the availability query referenced a total_units column that does not exist."),
    "US-051-01": ("Done", "No-show Processing (mockup 051) at /reservations/no-show, with the per-arrival screen at /reservations/no-show/{unitId} and a No-show action on the Front Desk Arrivals row where a missed arrival is actually noticed. GET /no-show-candidates lists arrivals due on or before today that are still 'reserved', with days overdue, stay value and amount paid. The detail screen carries the mockup's panels: Stay & Financial Summary, No-show Penalty Calculation, Room Release & Inventory, Refund / Deposit Handling, Reason & Notes. Closes a hole this session created: Arrivals deliberately keeps anyone who never checked in, so without this the list only grew. Verified in Chrome on CBR39535923."),
    "US-051-02": ("Done", "Primary workflow: POST /reservation-units/{id}/no-show charges the penalty, releases the room and the nights, and moves the unit to 'no_show' - a status the schema has always allowed and nothing had ever set. A no-show is NOT a cancellation: the guest did not call it off, and the difference matters to the penalty and to any later question about why a room sat empty. Penalty bases are 1 Night Room + Tax / 1 Night Room / Full Stay / No Penalty, priced from the property's cancellation policy; the tax is read from finance.tax_rules using the same rule tax_engine applies to a folio (one default tax group plus every stacking levy), so the figure here and the figure on the guest's bill are the same figure. Deposit handling offers retain-as-penalty / refund-in-full / retain-in-full with a live refund preview. When every unit is closed the reservation moves to completed. Verified: Anil Kapoor penalty Rs 6,895 posted as no_show_penalty Rs 6,500 + no_show_penalty_tax Rs 395 (26,000 x 5% + Rs 20 + Rs 50 per night = Rs 1,580 for the full stay), 4 nights returned to inventory, room released, refund of Rs 3,105 flagged."),
    "US-051-03": ("Done", "Security/exceptions: RBAC reservations.view / edit deny-by-default; 'No Penalty' is a WAIVER so it is hidden from anyone without reservations.approve and rejected with 403 if sent anyway. Verified: marking a no-show twice -> 422; a guest not yet due -> 422 naming the arrival date; a checked-in guest -> 422 'they did arrive'; a cancelled or checked-out unit -> 422. Marking a no-show does NOT move money back - any refund is estimated, flagged in the response and processed from the folio. Append-only audit reservation_unit.no_show with the basis, penalty, refund and whether the room was released."),
    "US-026-01": ("Done", "Property Settings view: GET /iam/properties/{id}/settings, RBAC-guarded (property.view), cross-tenant denied. Live in Settings screen. Verified."),
    "US-026-02": ("Done", "Property Settings primary workflow: PUT with optimistic locking (stale version -> 409), validation, persists; edit form live. Verified end-to-end."),
    "US-026-03": ("Done", "Security/exceptions: deny-by-default permission check (unauthorized -> 403), append-only audit_events with actor/before/after/reason/correlation. Verified: 403 for no-permission user, audit row on update."),
    "US-039-01": ("Done", "User Management view/search matches mockup 039, fully live: rich columns (Employee ID, Department, Properties, Roles chips, Status, Last Login, MFA, Active Sessions) from real IAM joins; server-side filters Role/Property/Department/Status + search; KPI cards from /users/stats. Verified all filters return correct rows."),
    "US-039-02": ("Done", "Primary workflow fully live: invite/create (+membership+employee), edit, activate/suspend, revoke-sessions; RBAC + audit; UI actions menu wired to real endpoints. Verified: revoke dropped active_sessions 12->10, edit/suspend reflect."),
    "US-039-03": ("Done", "Security/exceptions: deny-by-default (403), cannot self-deactivate, append-only audit for all actions incl revoke_sessions; View Activity shows real audit trail. Verified 403 + audit entries."),
    "US-040-01": ("Done", "Invite/Edit User Access screen (mockup 040) view: loads live roles+departments+property; Edit mode loads current access (GET /users/{id}/access: roles, department, settings). RBAC user.view. Verified."),
    "US-040-02": ("Done", "Dual-purpose primary workflow: INVITE (POST /invitations creates invited user+membership+employee+roles+settings) and EDIT (PUT /users/{id}/access updates name/department/employee, replaces role assignment set, MFA + settings, optimistic-locked). Verified: invite Deepa Iyer; edit changed roles 2->1 + MFA off, reflected in Users list."),
    "US-040-03": ("Done", "Security/exceptions: RBAC user.create (invite) + user.update (edit) deny-by-default -> 403; optimistic version conflict -> 409; append-only audit invitation.create + user.access.update with before/after; cross-tenant rejected. Verified 403 + audit rows."),
    "US-041-01": ("Done", "Roles & Permission Matrix (mockup 041) view: 3-column layout, roles list with user counts, catalogue 13 modules x 7 actions, matrix loads role's permission grid + scope/limits. RBAC role.view. Verified."),
    "US-041-02": ("Done", "Primary workflow: toggle module.action permissions, set property/record scope + max discount/refund, Save (PUT replaces role_permissions + updates scope/limits), Add Role, Clone Role (copies perms). Verified save round-trips + reload reflects + add/clone."),
    "US-041-03": ("Done", "Security/exceptions: RBAC role.view/role.manage deny-by-default (unauthorized -> 403); append-only audit role.matrix.update/role.create/role.clone with before/after granted counts. Verified 403 + audit entries. Makes role permissions real for User Mgmt chips + Invite access preview."),
    "US-042-01": ("Done", "Approval Queue (mockup 042) view: tabs Queue/Rules/History, filter chips (All/Discounts/Refunds/Rate Overrides/Other), request cards with requested-by/entity/policy/amount/due-in countdown; RBAC approval.view. Verified queue=4 with live due-in + category filter."),
    "US-042-02": ("Done", "Primary workflow: rule detail panel (name, applies-to, initiator/approver role chips, threshold, two-level/self-approval toggles) + Approve/Reject -> POST approve/reject, append-only approval_decisions, status transitions, moves to History. Verified approve dropped queue 4->3, appears in history."),
    "US-042-03": ("Done", "Security/exceptions: RBAC approval.view/decide deny-by-default (unauthorized -> 403); prohibit-self-approval guard (initiator cannot approve own -> 409); append-only audit approval.approved/rejected. Verified 403 + audit approval.approved."),
    "US-043-01": ("Done", "Audit Log (mockup 043) view: GET /audit/events org-scoped with filters (action, module/entity, search) + derived risk badges; events table over real iam.audit_events (25+ events from all screens). RBAC audit.view. Verified real events + filters."),
    "US-043-02": ("Done", "Primary workflow: filter/search/drill-down; Event Details panel with actor/action/module/entity/result/correlation + redacted before/after JSON via GET /audit/events/{id}. Verified detail with before/after on role.matrix.update. EXTENDED: GET /audit/events now takes entity_id as a comma-separated SET, so another screen can scope the trail to one record whose history spans several rows (a reservation plus its deposit instalments); /admin/audit reads ?entity_id= and ?scope_label= from the URL and shows a banner naming the scope with a Show all activity escape. Verified: 11 events scoped to CBR39535923, 0 for a bogus id, 163 unscoped."),
    "US-043-03": ("Done", "Security/exceptions: append-only (no edit/delete); RBAC audit.view deny-by-default (unauthorized -> 403); cross-tenant events excluded; before/after redacted. Verified 403 + org-scoped read."),
    "US-028-01": ("Done", "Reservations list/details (mockup 028) view: GET /reservations property-scoped list with status filter + search by number/guest, joins guest name + room type + nights + unit count; searchable table. Verified 35 real reservations, status filter, search. REWORKED for legibility: dates render as '6 Sep 2026' (was raw ISO) with a relative badge on arrival (Today / Tomorrow / in N days / N days ago) so near-identical rows can be told apart and past-dated arrivals stand out; the arrival window filter (arrival_from/arrival_to) is now exposed with Today / Next 7 days presets - the API had supported it since US-028 but no control existed; result count and per-filter empty states ('No reservations arrive on 9 Sep 2026', 'No reservations are cancelled') with a Clear all filters action. IMPORTANT DATA FIX: the list and detail queries returned COALESCE(g.full_name, 'Guest'), so 32 of 35 reservations with no primary_guest_id displayed the literal word 'Guest' as if it were a name; guest_name is now nullable and the UI shows a muted 'No guest on file'. Consumers updated (Reservations, Deposit Schedule, and Checkout Folio, whose initials avatar would have thrown on null)."),
    "US-028-02": ("Done", "Primary workflow: reservation detail drawer via GET /reservations/{id}/detail (units: room type, dates, nights, adults/children, per-unit status, assigned room); New Reservation success routes here. Verified detail returns units. EXTENDED: the drawer selection now lives in the URL (/reservations?id=<uuid>), so other screens can link straight to one reservation and Back closes the drawer; the header reads the number from the detail, not the list row, so a linked-to reservation renders even when the current filter excludes it. Detail also returns assigned_room_id (not just the room code) so screens can link to the room. Verified deep link opens CBR016915AE with the row highlighted."),
    "US-001-01": ("Done", "Dashboard view/search: live KPIs, room status, arrivals, 7-day chart from /flows/dashboard (booking-core + finance). Verified end-to-end."),
    "US-001-02": ("Done", "Dashboard primary workflow: real aggregated metrics via gateway; auto-refresh; verified with seeded + live bookings."),
    "US-001-03": ("Not Started", "Security/exceptions pending: auth/RBAC/audit not yet implemented."),
    "US-004-02": ("Done", "New Reservation primary workflow: stay+availability -> guest -> confirm -> advance payment (finance) -> folio balance. Verified end-to-end via UI and gateway."),
    "US-004-01": ("Integration", "Create flow live; reservation list/search view still pending."),
    "US-004-03": ("Not Started", "Security/exceptions pending: auth/RBAC/audit not yet implemented."),
    "US-060-01": ("Done", "Room Type Management (mockup 060) rebuilt as a real screen at /property/room-types (also a tab on Rooms). 4 KPI cards from GET /room-types/stats (room types active/inactive, total keys active/inactive, max guest capacity, average base rate); search by name/code; Status + Room View + Sort By filters server-side; table with thumbnail, name+description, code, total/active rooms, base rate, status. RBAC rooms.view. Verified 4 types, KPIs 4/44/132/6500."),
    "US-060-02": ("Done", "Right-hand Edit Room Type panel matches the mockup: photo gallery + Change Photo/Add More, Active toggle, name/code, description with 500-char counter, Max Occupancy, Child Policy, Room Size, Bed Configuration, Extra Bed Option (+charge), Base Rate, Room View, Default Rate Plan, per-type amenity checklist, and Created by / Last modified audit lines. Actions: Save Changes, Duplicate (clones fields + amenities as inactive), Deactivate/Activate. Optimistic locking. Verified duplicate 201 and amenity checklist round-trip. NOTE: photo UPLOAD is not wired - property.room_type_photos and the gallery render real photos when present, but there is no upload endpoint yet."),
    "US-065-01": ("Done", "Guest directory (mockup 010) view/search: GET /booking/guests org-scoped list + name/phone/email search; searchable table with avatar/name/email/phone/nationality. Verified 7 real guests + search."),
    "US-065-02": ("Done", "Guest primary workflow: Add Guest (POST /guests) + Edit Guest (PATCH /guests/{id}) via modal, GET /guests/{id} detail. Verified create + edit persist against real data."),
    "US-010-01": ("Done", "Guest Directory view/search implemented as the Guests screen (shared with US-065): live searchable directory over engagement.guests. Verified."),
    "US-010-02": ("Done", "Guest Directory primary workflow: add/edit guests live. Verified create/edit."),
    "US-007-01": ("Done", "Checkout & Guest Folio (mockup 007) REBUILT as the real screen at /front-desk/check-out/{unitId}. Previously /reservations/{id}/folio showed a folio and could take a payment but had NO way to check anyone out - the engine (flow.check_out) had existed since the first migration and nothing ever called it, so a guest could be checked in and could pay and could never leave. Now: a Departures list beside Arrivals on the Front Desk (GET /booking/departures) showing room, guest, balance and a status badge - Due Out Today, Overdue by N days, Checked out - where an overstay stays on the list whatever date is asked for; and GET /reservation-units/{id}/check-out-view returning the guest, room, folio lines with Department and Qty, and the full summary (subtotal / taxes / grand total / advance paid / balance due / deposit held). Breadcrumb reads Front Desk / Departures / Room 101 as the mockup does. Verified in Chrome on CBR24107 room 101."),
    # ---- Room Block & Out of Order (screen 063), shipped 2026-09-08 ----
    "US-063-01": ("Done", "Room Block and Out of Order (mockup 063) at /rooms/blocks and as the Rooms > Blocks tab. 4 KPI cards from GET /room-blocks/stats (Currently Blocked, Out of Order, Due to End Today, Total Rooms Unavailable). Calendar View renders month bars colour-coded Blocked / Out of Order / Maintenance with 'rooms | reason' labels; List View is the mockup's 'Active Blocks and Out of Order Rooms' table. Filters: Room Type, Status, search by room/reason/reference. Multi-room blocks are grouped so '101 - 104' reads as one line. RBAC rooms.view. Verified live."),
    "US-063-02": ("Done", "Create Block panel matches the mockup: Block Type radio (Room Block / Out of Order), Select Rooms chips with 'N room(s) selected', Reason Category, Reason with 500-char counter, Start/End dates, Severity, Link to Maintenance, and the Inventory Impact notice. Actions: Create Block, Clear, End Early and Cancel per block. Verified through the UI: 'Blocked 4 room(s)' and the grouped row '101 - 104 | Room Block | Maintenance - Scheduled | active' with End Early / Cancel."),
    "US-063-03": ("Done", "KEY INVARIANT: a block cannot overlap a reservation or another block on the same room. This is NOT reimplemented - creating a block inserts a booking.room_calendar_entries row of kind 'maintenance', so the existing GiST exclusion constraint (schema 4) is the arbiter for both reservations and blocks. Multi-room requests are partially successful by design: free rooms block, clashing rooms return per-room conflicts. VERIFIED: (a) block over an existing block -> refused per room; (b) block over a live assigned reservation -> refused; (c) non-overlapping dates on the same room -> allowed; (d) End Early releases the calendar so the freed dates become blockable again. Security: RBAC rooms.view/rooms.edit deny-by-default (401/403), cross-tenant -> 403, end date before start -> 422, invalid block_type/severity/category -> 422, stale version -> 409. Append-only audit room_block.create/end/cancel/update."),
    # ---- Buildings & Floors (screen 061), shipped 2026-09-08 ----
    "US-061-01": ("Done", "Buildings & Floors (mockup 061) view at /property/buildings, also in the Property menu. Left tree lists buildings (name, N Floors | N Rooms, Active/Inactive) with expandable floors showing 'Floor Name (Code)', declared room range and live room count. Room counts are always derived from rooms actually linked to the floor, never from the range, so the two can be compared instead of silently disagreeing. RBAC rooms.view. Verified: Bay View Wing / First Floor (1) / Rooms 101-144 / 44 Rooms from real data."),
    "US-061-02": ("Done", "Primary workflow: Add Building, Add floor to <building>, and the Edit Floor panel (Building, Floor Name, Floor Code with the room-number hint, From/To Room No., read-only Total Rooms, Display Order with its ordering hint, Status, Audit Information). Actions: Save Changes, Move Rooms (reassigns rooms to another floor, updating building_id/floor_id and the legacy text column together), Deactivate/Activate, and Reorder mode for buildings and floors (POST /buildings/reorder, /floors/reorder). Optimistic locking throughout. Verified create building 201, create floor 201, reorder, and move-rooms."),
    "US-061-03": ("Done", "Security/exceptions: RBAC rooms.view / rooms.configure deny-by-default (401 no token, 403 no permission); cross-tenant property_id -> 403; duplicate building code -> 409; duplicate floor code within a building -> 409; stale version -> 409; invalid status -> 422; move-rooms to the same floor -> 422 and to a missing floor -> 404. KEY RULE: a floor (or building) cannot be deactivated while its rooms hold live reservations - GET /floors/{id} returns can_deactivate + blocker_message so the screen explains the block up front, and the write path enforces it again. Verified end-to-end: deactivate returned 409 '1 active reservation(s) still use rooms on this floor' while an assignment existed, then 200 once released. Append-only audit for building.create/update/reorder and floor.create/update/move_rooms/reorder."),
    # ---- Rooms cluster (screens 008 / 059 / 060 / 062), shipped 2026-09-08 ----
    "US-008-01": ("Done", "Rooms & Villas Inventory (mockup 008) view/search: GET /booking/rooms property-scoped grid+list with live KPI cards (total/occupied/available/cleaning/maintenance) and server-side Floor/Room Type/Status filters over 44 real rooms. Occupancy and housekeeping state are DERIVED at query time from booking.stays/reservation_units and operations.room_condition, never stored. RBAC rooms.view. Verified: 44 rooms, state=cleaning returns 24."),
    "US-008-02": ("Done", "Inventory primary workflow: grid/list toggle, Add Room, View, Assign (real reservation assignment via the GiST-guarded flow endpoint) and Block/Unblock. The Blocks tab now hosts the full Room Block & Out of Order screen (063) rather than a placeholder list. Verified assign 200 + 409 on overlap, block round-trip. Remaining mockup gap: the 5th 'Rate Plans' tab is present but its module (screen 066) is not built."),
    "US-008-03": ("Done", "Security/exceptions: deny-by-default rooms.view (no token -> 401, no permission -> 403); cross-tenant property_id -> 403 via assert_property_in_org; blocking a room with an in-house stay -> 409 (guard implemented; not exercised - no in-house stays in current data); append-only audit room.block/room.unblock. Verified 401/403/403."),
    "US-059-01": ("Done", "Add or Edit Room (mockup 059) view: loads room + amenities + photos; Add mode seeds from /rooms/facets. Live Validation panel and Audit Information. Photos section now built - gallery renders uploaded photos with a Primary badge, backed by property.room_photos in MinIO with presigned URLs. RBAC rooms.view. Verified upload through the browser file input."),
    "US-059-02": ("Done", "Primary workflow: create/update covering basic info, occupancy, bed setup, view, base rate, housekeeping zone, accessibility, near-elevator, status/service status, notes and the amenity set. Photo upload / make-primary / delete. Footer now matches the mockup: Cancel, Save Draft (writes status='draft'), Save Room, Deactivate/Activate. Optimistic locking. Verified draft round-trip 200 and photo upload/delete."),
    "US-059-03": ("Done", "Security/exceptions: RBAC rooms.create / rooms.edit deny-by-default -> 403; stale version -> 409; duplicate room number -> 409; invalid accessibility/status enum -> 422; room type outside property -> 422; cross-tenant -> 403; append-only audit room.create/room.update with before/after. Verified 409/409/422/403."),
    "US-060-01": ("Done", "Room Type Management (mockup 060) rebuilt as a real screen at /property/room-types (also a tab on Rooms). 4 KPI cards from GET /room-types/stats (room types active/inactive, total keys active/inactive, max guest capacity, average base rate); search by name/code; Status + Room View + Sort By filters server-side; table with thumbnail, name+description, code, total/active rooms, base rate, status. RBAC rooms.view. Verified 4 types, KPIs 4/44/132/6500."),
    "US-060-02": ("Done", "Right-hand Edit Room Type panel matches the mockup: photo gallery + Change Photo/Add More, Active toggle, name/code, description with 500-char counter, Max Occupancy, Child Policy, Room Size, Bed Configuration, Extra Bed Option (+charge), Base Rate, Room View, Default Rate Plan, per-type amenity checklist, and Created by / Last modified audit lines. Actions: Save Changes, Duplicate (clones fields + amenities as inactive), Deactivate/Activate. Optimistic locking. Verified duplicate 201 and amenity checklist round-trip. NOTE: photo UPLOAD is not wired - property.room_type_photos and the gallery render real photos when present, but there is no upload endpoint yet."),
    "US-060-03": ("Done", "Security/exceptions: RBAC rooms.view / rooms.configure deny-by-default (401 no token, 403 no permission); cross-tenant property_id -> 403; duplicate code -> 409; stale version -> 409; max_occupancy below max_adults -> 422; deactivating a type still used by active rooms -> 409; append-only audit room_type.create/update/duplicate/active/inactive with before/after. Verified 409/409/422/403/401."),
    "US-062-01": ("Done", "Amenities Management (mockup 062) rebuilt as a real screen at /property/amenities (also a tab on Rooms). 4 KPI cards from GET /amenities/stats (total / guest visible / active / inactive); category tabs with live counts using the mockup's own vocabulary (In-Room, Bathroom, Technology, Food & Beverage, Recreation, Safety & Security - migrated from the invented general/comfort/kitchen/outdoor set); search + Status + Guest Visible filters + Reset; table with name, code, category, inline Guest Visible toggle, Assigned Room Types, status; server-side pagination 10/page. RBAC rooms.view. Verified 14 amenities, tab counts, toggle updates KPI live."),
    "US-062-02": ("Done", "Add/Edit Amenity panel matches the mockup: name, unique code with hint, Category, Icon, 'Visible to Guests' with explanation, Assign to Room Types chip multi-select, Status radio, Chargeable, Description with 300-char counter, Audit Information, Cancel/Save Amenity, and Other Actions - Merge Duplicate and Deactivate/Activate. Merge moves room and room-type assignments onto the survivor (skipping ones it already has) and retires the duplicate, all in one transaction. Verified merge moved the assignment and set the duplicate inactive."),
    "US-062-03": ("Done", "Security/exceptions: RBAC rooms.view / rooms.configure deny-by-default (401/403); cross-tenant -> 403; duplicate code -> 409; stale version -> 409; invalid category -> 422; merging an amenity into itself -> 422; merge target must exist in the same property -> 404; append-only audit amenity.create/update/merge with before/after. Verified 422 self-merge, 422 bad category, 403 cross-tenant, 401 unauthenticated."),
    "US-007-02": ("Done", "Primary workflow: POST /reservation-units/{id}/complete-check-out settles, closes the stay, frees the room and records the handover in ONE transaction, so a guest is never half-departed and a payment is never taken for a checkout that then fails. Takes the final payment (UPI/Card/Cash/Link) as a folio credit, optionally refunds the security deposit taken at check-in as a debit, then calls flow.check_out which closes the stay, releases future nights and sets the room_calendar_entry to released. Footer carries the mockup's three completion checkboxes (room key returned / housekeeping notified / feedback link scheduled) and a live 'Balance after this' figure. Migration 0016 adds booking.stay_checkouts recording settled_amount and balance_at_checkout AT THE MOMENT OF DEPARTURE - a folio keeps moving afterwards, so what a guest owed when they walked out is only answerable if written down then. Verified in Chrome: Sowmya Reddy room 101 -> unit checked_out, stay checked_out with actual_checkout_at set, room_calendar_entry released, checkout row with key_returned and housekeeping_notified true. The older /reservations/{id}/folio Add Charge + Collect Payment view remains for reservation-level folio work."),
}


def main() -> int:
    wb = openpyxl.load_workbook(FILE)
    ws = wb["User Stories & Acceptance"]

    # Column indices (1-based): C=3 id, X=24 status, Y=25 progress, AD=30 notes.
    ID_COL, STATUS_COL, PROG_COL, NOTES_COL = 3, 24, 25, 30

    updated = []
    for row in range(5, ws.max_row + 1):
        sid = ws.cell(row=row, column=ID_COL).value
        if sid in UPDATES:
            stage, note = UPDATES[sid]
            ws.cell(row=row, column=STATUS_COL).value = stage
            ws.cell(row=row, column=PROG_COL).value = STAGE[stage]
            ws.cell(row=row, column=NOTES_COL).value = note
            updated.append(f"{sid} -> {stage} ({STAGE[stage]:.0%})")

    wb.save(FILE)
    print("Updated rows:")
    for u in updated:
        print("  ", u)
    print(f"Total updated: {len(updated)} / {len(UPDATES)} target stories")
    missing = set(UPDATES) - {u.split(' ')[0] for u in updated}
    if missing:
        print("WARNING - not found in sheet:", missing)
    return 0


if __name__ == "__main__":
    sys.exit(main())
